// #Misfits Change - Mentor Help control code-behind (like BwoinkControl but limited verbs)
using System.Linq;
using System.Text;
using Content.Client.Administration.Managers;
using Content.Client.Administration.UI.CustomControls;
using Content.Client._Misfits.UserInterface.Systems.MentorHelp;
using Content.Shared.Administration;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Configuration;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.Administration.UI.MentorHelp;

[GenerateTypedNameReferences]
public sealed partial class MentorHelpControl : Control
{
    [Dependency] private readonly IClientAdminManager _adminManager = default!;
    [Dependency] private readonly IClientConsoleHost _console = default!;
    [Dependency] private readonly IUserInterfaceManager _ui = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    public AdminMentorHelpUIHandler MHelpHelper = default!;

    private PlayerInfo? _currentPlayer;

    public MentorHelpControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var uiController = _ui.GetUIController<MentorHelpUIController>();
        if (uiController.UIHelper is not AdminMentorHelpUIHandler helper)
            return;

        MHelpHelper = helper;

        _adminManager.AdminStatusUpdated += UpdateButtons;
        UpdateButtons();

        ChannelSelector.OnSelectionChanged += sel =>
        {
            _currentPlayer = sel;
            SwitchToChannel(sel?.SessionId);
            ChannelSelector.PlayerListContainer.DirtyList();
        };

        ChannelSelector.OverrideText += (info, text) =>
        {
            var sb = new StringBuilder();

            if (info.Connected)
                sb.Append('●');
            else
                sb.Append(info.ActiveThisRound ? '○' : '·');

            sb.Append(' ');
            if (MHelpHelper.TryGetChannel(info.SessionId, out var panel) && panel.Unread > 0)
            {
                if (panel.Unread < 11)
                    sb.Append(new Rune('➀' + (panel.Unread - 1)));
                else
                    sb.Append(new Rune(0x2639)); // ☹
                sb.Append(' ');
            }

            if (info.OverallPlaytime <= TimeSpan.FromSeconds(_cfg.GetCVar(CCVars.NewPlayerThreshold)))
                sb.Append(new Rune(0x23F2)); // ⏲

            sb.AppendFormat("\"{0}\"", text);

            return sb.ToString();
        };

        ChannelSelector.Comparison = (a, b) =>
        {
            var ach = MHelpHelper.EnsurePanel(a.SessionId);
            var bch = MHelpHelper.EnsurePanel(b.SessionId);

            // Pinned players first
            if (a.IsPinned != b.IsPinned)
                return a.IsPinned ? -1 : 1;

            var aUnread = ach.Unread > 0;
            var bUnread = bch.Unread > 0;
            if (aUnread != bUnread)
                return aUnread ? -1 : 1;

            var aRecent = a.ActiveThisRound && ach.LastMessage != DateTime.MinValue;
            var bRecent = b.ActiveThisRound && bch.LastMessage != DateTime.MinValue;
            if (aRecent != bRecent)
                return aRecent ? -1 : 1;

            if (a.Connected != b.Connected)
                return a.Connected ? -1 : 1;

            if (a.Connected && b.Connected)
            {
                var aNewPlayer = a.OverallPlaytime <= TimeSpan.FromMinutes(_cfg.GetCVar(CCVars.NewPlayerThreshold));
                var bNewPlayer = b.OverallPlaytime <= TimeSpan.FromMinutes(_cfg.GetCVar(CCVars.NewPlayerThreshold));

                if (aNewPlayer != bNewPlayer)
                    return aNewPlayer ? -1 : 1;
            }

            if (!a.Connected && !b.Connected)
            {
                if (a.ActiveThisRound != b.ActiveThisRound)
                    return a.ActiveThisRound ? -1 : 1;
            }

            return bch.LastMessage.CompareTo(ach.LastMessage);
        };

        Notes.OnPressed += _ =>
        {
            if (_currentPlayer is not null)
                _console.ExecuteCommand($"adminnotes \"{_currentPlayer.SessionId}\"");
        };

        PopOut.OnPressed += _ =>
        {
            uiController.PopOut();
        };
    }

    public void OnMentorHelp(NetUserId channel)
    {
        ChannelSelector.PopulateList();
    }

    public void SelectChannel(NetUserId channel)
    {
        if (!ChannelSelector.PlayerInfo.TryFirstOrDefault(
            i => i.SessionId == channel, out var info))
            return;

        var data = new PlayerListData(info);
        if (!ChannelSelector.PlayerListContainer.Data.Contains(data))
        {
            ChannelSelector.StopFiltering();
        }

        ChannelSelector.PopulateList();
        ChannelSelector.PlayerListContainer.Select(data);
    }

    public void UpdateButtons()
    {
        var disabled = _currentPlayer == null;

        // Only show Notes button for mentors with ViewNotes permission
        Notes.Visible = _adminManager.HasFlag(AdminFlags.ViewNotes);
        Notes.Disabled = !Notes.Visible || disabled;
    }

    private void SwitchToChannel(NetUserId? ch)
    {
        UpdateButtons();

        if (ch != null)
        {
            MHelpHelper.HideAllPanels();
            var panel = MHelpHelper.EnsurePanel(ch.Value);
            panel.Visible = true;
        }
    }

    public void PopulateList()
    {
        var pinnedPlayers = ChannelSelector.PlayerInfo.Where(p => p.IsPinned).ToDictionary(p => p.SessionId);

        ChannelSelector.PopulateList();

        foreach (var player in ChannelSelector.PlayerInfo)
        {
            if (pinnedPlayers.TryGetValue(player.SessionId, out var pinnedPlayer))
            {
                player.IsPinned = pinnedPlayer.IsPinned;
            }
        }

        UpdateButtons();
    }
}
